export const ALAHLY_MATCH_PKS_CONFIG = {
    homeLabel: "الأهلي",
    homePlayerField: "AHLY PLAYER",
    homeGkField: "AHLY GK",
    homeStatusField: "AHLY STATUS",
    homeHowMissField: "HOWMISS AHLY",
    oppPlayerField: "OPPONENT PLAYER",
    oppGkField: "OPPONENT GK",
    oppStatusField: "OPPONENT STATUS",
    oppHowMissField: "HOWMISS OPPONENT",
    homeScoreField: "G-AHLY",
    oppScoreField: "G-OPPONENT",
    pksWlField: "PKS W-L",
    systemField: "PKS SYSTEM",
    whoStartField: "WHO START?",
    pksIdField: "PKS_ID",
    homeGkStatusField: "OPPONENT STATUS",
    oppGkStatusField: "AHLY STATUS",
    homeGkHowField: "HOWMISS OPPONENT",
    oppGkHowField: "HOWMISS AHLY",
    homeTabPlayers: "ahly_players",
    homeTabGks: "ahly_gks",
    homeTabLabel: "AL AHLY PLAYERS",
    homeGkTabLabel: "AL AHLY GKs",
    goalStatusIncludes: (status) => String(status || "").toUpperCase().includes("GOAL"),
};

export const EGYPT_NT_MATCH_PKS_CONFIG = {
    homeLabel: "مصر",
    homePlayerField: "Egypt PLAYER",
    homeGkField: "EGYPT GK",
    homeStatusField: "Egypt STATUS",
    homeHowMissField: "EGYPT HOW MISS",
    oppPlayerField: "OPPONENT PLAYER",
    oppGkField: "OPPONENT GK",
    oppStatusField: "OPPONENT STATUS",
    oppHowMissField: "OPPONENT HOW MISS",
    homeScoreField: "G-EGYPT",
    oppScoreField: "G-OPPONENT",
    pksWlField: "PKS W-L",
    systemField: "PKS System",
    whoStartField: null,
    pksIdField: "DISPLAY_ID",
    homeGkStatusField: "OPPONENT STATUS",
    oppGkStatusField: "Egypt STATUS",
    homeGkHowField: "OPPONENT HOW MISS",
    oppGkHowField: "EGYPT HOW MISS",
    homeTabPlayers: "egypt_players",
    homeTabGks: "egypt_gks",
    homeTabLabel: "EGYPT PLAYERS",
    homeGkTabLabel: "EGYPT GKs",
    goalStatusIncludes: (status) => {
        const s = String(status || "").toUpperCase();
        return s.includes("GOAL") || s === "G";
    },
};
