-- One-time: add temporary column for Egypt NT MATCH_ID migration.
ALTER TABLE "egy_NT_MATCHDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "egy_NT_LINEUPDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "egy_NT_PLAYERDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "egy_NT_GKSDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "egy_NT_PKS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
