-- One-time: add temporary column for Al Ahly MATCH_ID migration.
-- Drop with scripts/drop-alahly-match-id-temp.sql after validate.

ALTER TABLE "alahly_MATCHDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "alahly_LINEUPDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "alahly_PLAYERDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "alahly_GKSDETAILS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "alahly_PKS" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
ALTER TABLE "alahly_MEDIATRACKER" ADD COLUMN IF NOT EXISTS "MATCH_ID_TEMP" text;
