-- After successful migration + validate, remove temporary columns.

ALTER TABLE "alahly_MATCHDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "alahly_LINEUPDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "alahly_PLAYERDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "alahly_GKSDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "alahly_PKS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "alahly_MEDIATRACKER" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
