-- Drop temporary columns after Egypt NT MATCH_ID migration validate.
ALTER TABLE "egy_NT_MATCHDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "egy_NT_LINEUPDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "egy_NT_PLAYERDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "egy_NT_GKSDETAILS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
ALTER TABLE "egy_NT_PKS" DROP COLUMN IF EXISTS "MATCH_ID_TEMP";
