-- Allow empty Arabic catalog names when English name is provided.
-- Replaces full UNIQUE(name) with partial unique index on non-empty Arabic names only.

ALTER TABLE "db_MANAGERS" DROP CONSTRAINT IF EXISTS "db_MANAGERS_MANAGER_NAME_key";
ALTER TABLE "db_MANAGERS" ALTER COLUMN "MANAGER_NAME" DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "db_managers_manager_name_nonempty_unique"
    ON "db_MANAGERS" ("MANAGER_NAME")
    WHERE "MANAGER_NAME" IS NOT NULL AND BTRIM("MANAGER_NAME") <> '';

ALTER TABLE "db_PLAYERS" DROP CONSTRAINT IF EXISTS "db_PLAYERS_PLAYER_NAME_key";
ALTER TABLE "db_PLAYERS" ALTER COLUMN "PLAYER_NAME" DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "db_players_player_name_nonempty_unique"
    ON "db_PLAYERS" ("PLAYER_NAME")
    WHERE "PLAYER_NAME" IS NOT NULL AND BTRIM("PLAYER_NAME") <> '';

ALTER TABLE "db_REFEREES" DROP CONSTRAINT IF EXISTS "db_REFEREES_REFEREE_NAME_key";
ALTER TABLE "db_REFEREES" ALTER COLUMN "REFEREE_NAME" DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "db_referees_referee_name_nonempty_unique"
    ON "db_REFEREES" ("REFEREE_NAME")
    WHERE "REFEREE_NAME" IS NOT NULL AND BTRIM("REFEREE_NAME") <> '';

ALTER TABLE "db_TEAMS" DROP CONSTRAINT IF EXISTS "db_TEAMS_TEAM_NAME_key";
ALTER TABLE "db_TEAMS" ALTER COLUMN "TEAM_NAME" DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "db_teams_team_name_nonempty_unique"
    ON "db_TEAMS" ("TEAM_NAME")
    WHERE "TEAM_NAME" IS NOT NULL AND BTRIM("TEAM_NAME") <> '';

ALTER TABLE "db_STADIUMS" DROP CONSTRAINT IF EXISTS "db_STADIUMS_STADIUM_NAME_key";
ALTER TABLE "db_STADIUMS" ALTER COLUMN "STADIUM_NAME" DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "db_stadiums_stadium_name_nonempty_unique"
    ON "db_STADIUMS" ("STADIUM_NAME")
    WHERE "STADIUM_NAME" IS NOT NULL AND BTRIM("STADIUM_NAME") <> '';

ALTER TABLE "db_COUNTRIES" ALTER COLUMN "COUNTRY_NAME" DROP NOT NULL;
ALTER TABLE "db_COUNTRIES" ALTER COLUMN "COUNTRY_NAME_EN" DROP NOT NULL;
