ALTER TABLE "alahly_MATCHDETAILS"
    ADD COLUMN IF NOT EXISTS "FINAL_ID" TEXT,
    ADD COLUMN IF NOT EXISTS "W-D-L FINAL" TEXT;

ALTER TABLE "alahly_LINEUPDETAILS"
    ADD COLUMN IF NOT EXISTS "FINAL_ID" TEXT;

ALTER TABLE "alahly_PLAYERDETAILS"
    ADD COLUMN IF NOT EXISTS "FINAL_ID" TEXT;

CREATE INDEX IF NOT EXISTS idx_alahly_match_final_id
    ON "alahly_MATCHDETAILS" ("FINAL_ID");
