-- Bilingual name columns for global catalog tables (mirrors db_COUNTRIES pattern)

ALTER TABLE "db_PLAYERS" ADD COLUMN IF NOT EXISTS "PLAYER_NAME_EN" text;
ALTER TABLE "db_MANAGERS" ADD COLUMN IF NOT EXISTS "MANAGER_NAME_EN" text;
ALTER TABLE "db_REFEREES" ADD COLUMN IF NOT EXISTS "REFEREE_NAME_EN" text;
ALTER TABLE "db_TEAMS" ADD COLUMN IF NOT EXISTS "TEAM_NAME_EN" text;
ALTER TABLE "db_STADIUMS" ADD COLUMN IF NOT EXISTS "STADIUM_NAME_EN" text;

CREATE INDEX IF NOT EXISTS idx_db_players_name_en ON "db_PLAYERS" ("PLAYER_NAME_EN");
CREATE INDEX IF NOT EXISTS idx_db_managers_name_en ON "db_MANAGERS" ("MANAGER_NAME_EN");
CREATE INDEX IF NOT EXISTS idx_db_referees_name_en ON "db_REFEREES" ("REFEREE_NAME_EN");
CREATE INDEX IF NOT EXISTS idx_db_teams_name_en ON "db_TEAMS" ("TEAM_NAME_EN");
CREATE INDEX IF NOT EXISTS idx_db_stadiums_name_en ON "db_STADIUMS" ("STADIUM_NAME_EN");
